@startuml
class BinaryNumber {
  + parseToDecimalNumber(): double
}
class Calculator {
  + divide(Number, Number): String
  + sum(Number, Number): String
  + subtract(Number, Number): String
  + multiply(Number, Number): String
  + verifyNonZeroDivision(Number): boolean
}
class ComplexNumber {
  - realPart: double
  - imaginaryPart: double
  + parseToDecimalNumber(): double
}
class DecimalNumber {
  + parseToDecimalNumber(): double
}
class HexaDecimalNumber {
  + parseToDecimalNumber(): double
}
class Number {
  - number: String
  + toString(): String
  + parseToDecimalNumber(): double
}
class OctalNumber {
  + parseToDecimalNumber(): double
}
class RomanNumber {
  + parseToDecimalNumber(): double
}

Calculator -u-> Number

BinaryNumber       --|>  Number
ComplexNumber      --|>  Number
DecimalNumber      --|>  Number
HexaDecimalNumber  --|>  Number
OctalNumber        --|>  Number
RomanNumber        --|>  Number
@enduml
