@startuml
class BinaryNumber {
  + parse(int): NumberType
}
class Calculator {
  - result: NumberType
  - secondNumber: NumberType
  - firstNumber: NumberType
  + sum(): NumberType
  + subtract(): NumberType
  + canBeCalculated(int, int): boolean
  + parseNumber(String, int): int
  + multiply(): NumberType
  + createArithmeticException(boolean): void
  + divide(): NumberType
}
class HexaDecimalNumber {
  + parse(int): NumberType
}
class Main {
  + main(String[]): void
}
class NumberType {
  - radix: int
  + REAL_RADIX: int
  + BINARY_RADIX: int
  + HEXADECIMAL_RADIX: int
  - number: String
  + OCTAL_RADIX: int
  + getNumber(): String
  + parse(int): NumberType
  + getRadix(): int
  + toString(): String
}
class OctalNumber {
  + parse(int): NumberType
}
class RealNumber {
  + parse(int): NumberType
}

BinaryNumber       --|>  NumberType
HexaDecimalNumber  --|>  NumberType
OctalNumber        --|>  NumberType
RealNumber         --|>  NumberType
@enduml